apiVersion: v1
kind: Service
metadata:
  name: gosample
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gosample
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosample
  template:
    metadata:
      labels:
        app: gosample
    spec:
      containers:
      - name: gosample
        image: kubreg.azurecr.io/gosample
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
